spring:
  datasource:
    dynamic:
      p6spy: true
      datasource:
        master:
    username: root
    password: wujiawei
    url: jdbc:mysql://easy.com:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver