spring:
  datasource:
    dynamic:
      p6spy: true
      datasource:
        master:
          username: root
          password: wujiawei
          url: jdbc:mysql://www.wu2020.top:3306/temp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver