server:
  port: 1180

spring:
  #数据库配置
  datasource:
    username: root
    password: wujiawei
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.wu2020.top:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    platform: h2
    continue-on-error: true
