server:
  port: 1180

spring:
  datasource:
    dynamic:
      p6spy: false
      datasource:
        master:
          username: root
          password: wujiawei
          url: jdbc:mysql://www.wu2020.top:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
        upsert:
          username: root
          password: wujiawei
          url: jdbc:mysql://k8s.wu2020.top:13306/upsert?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver


