server:
  port: 1180

spring:
  profiles:
    active: empty

  #  elasticsearch:
  #    rest:
  #      uris: "http://k8s.wu-framework.com:9200"
  jpa:
    show-sql: true
  activemq:
    broker-url: 127.0.0.1:6631
  redis:
    host: easy.com
    password: 123456
  rsocket:
    server:
      address: 127.0.0.1
  application:
    name: temple
  easy:
    upsert:
      config:
        print-sql: true
        batch-limit: 10000
        record-log: true
  hbase:
    zookeeper-quorum: 'k8s.wu-framework.com:2181'



debug: false

nacos:
  config:
    server-addr: easy.com:8848
    namespace: public

