server:
  port: 1180

spring:
  profiles:
    active: h2

#  elasticsearch:
#    rest:
#      uris: "http://k8s.wu2020.top:9200"
  jpa:
    show-sql: true
  activemq:
    broker-url: 127.0.0.1:6631
  redis:
    host: www.wu2020.top
    password: 123456
  rsocket:
    server:
      address: 127.0.0.1
  application:
    name: temple
  easy:
    upsert:
      config:
        print-sql: true
        batch-limit: 10000
        record-log: true
  hbase:
    zookeeper-quorum: 'k8s.wu2020.top:2181'



debug: false

nacos:
  config:
    server-addr: www.wu2020.top:8848
    namespace: public

